---
name: mvn
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  mvn:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2022, macos-12]
        java: [11, 17]
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: java -version
      - run: mvn -version
      - run: mvn --errors --batch-mode -"Dinvoker.skip" -"DskipITs" clean install -Pqulice
